apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue
spec:
  selector:
    matchLabels:
      app: blue
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
      - name: blue
        image: avinashdesireddy/colored-canavas:v2 

---
apiVersion: v1
kind: Service
metadata:
  name: blue-svc
spec:
  type: NodePort
  selector:
    app: blue
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
