apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue
spec:
  selector:
    matchLabels:
      app: blue
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
      - name: blue
        image: avinashdesireddy/colored-canavas:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: COLOR
          value: "blue"
        - name: TITLE
          value: "BLUE: OPA Demo"
        - name: DESCRIPTION
          value: ""

---
apiVersion: v1
kind: Service
metadata:
  name: blue-svc
spec:
  type: NodePort
  selector:
    app: blue
  ports:
  - port: 8080
    targetPort: 8080
