apiVersion: apps/v1
kind: Deployment
metadata:
  name: red
spec:
  selector:
    matchLabels:
      app: red
  template:
    metadata:
      labels:
        app: red
    spec:
      containers:
      - name: red
        image: avinashdesireddy/colored-canavas:v1
        imagePullPolicy: Always
        env:
        - name: COLOR
          value: "red"
        - name: TITLE
          value: "RED: OPA Demo"
        - name: DESCRIPTION
          value: ""

---
apiVersion: v1
kind: Service
metadata:
  name: red-svc
spec:
  type: NodePort
  selector:
    app: red
  ports:
  - port: 8080
    targetPort: 8080